services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: air_quality_db
    ports:
      - "5432:5432"
    networks:
      - air_quality_network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - air_quality_network

networks:
  air_quality_network:
    driver: bridge
